Collection = {
    "ANGRY": [
    { "url": "https://i.imgur.com/5uf11DN.gif", "name": "Murenase! Seton Gakuen" },
    { "url": "https://i.imgur.com/61ob1QU.gif", "name": "Kobayashi-san Chi no Maid Dragon" },
    { "url": "https://i.imgur.com/wNEDuvs.gif", "name": "Haikyū!!" },
    { "url": "https://i.imgur.com/RIPSkP8.gif", "name": "Toradora!" },
    { "url": "https://i.imgur.com/jssf6uW.gif", "name": "Kobayashi-san Chi no Maid Dragon S" },
    { "url": "https://i.imgur.com/o3SmfGX.gif", "name": "Noragami" },
    { "url": "https://i.imgur.com/XiApV4Q.gif", "name": "Nisekoi" },
    { "url": "https://i.imgur.com/bZ4CWTF.gif", "name": "Kobayashi-san Chi no Maid Dragon" },
    { "url": "https://i.imgur.com/NF0VeFa.gif", "name": "One Punch Man" },
    { "url": "https://i.imgur.com/B7U2yxm.gif", "name": "Hitori Bocchi no Marumaru Seikatsu" },
    { "url": "https://i.imgur.com/uivh2ou.gif", "name": "Kiznaiver" },
    { "url": "https://i.imgur.com/BM5xyQI.gif", "name": "Toradora!" },
    { "url": "https://i.imgur.com/FsdxPsp.gif", "name": "Violet Evergarden" },
    { "url": "https://i.imgur.com/7zwYvM8.gif", "name": "Hataraku Maou-sama!" },
    { "url": "https://i.imgur.com/k2wI8YC.gif", "name": "Himouto! Umaru-chan" }
],
    "BAKA": [
    { "url": "https://i.imgur.com/tSCTSJv.gif", "name": "Ochikobore Fruit Tart" },
    { "url": "https://i.imgur.com/HGrcmAQ.gif", "name": "Katanagatari" },
    { "url": "https://i.imgur.com/2TvQSVg.gif", "name": "Kanojo, Okarishimasu" },
    { "url": "https://i.imgur.com/f2fPdOA.gif", "name": "Barakamon" },
    { "url": "https://i.imgur.com/tKYowgr.gif", "name": "Gake no ue no Ponyo" },
    { "url": "https://i.imgur.com/HjGztro.gif", "name": "Shokugeki no Sōma" },
    { "url": "https://i.imgur.com/0tontxP.gif", "name": "The Kingdom of Magic" },
    { "url": "https://i.imgur.com/dsVwXtZ.gif", "name": "Hensuki" },
    { "url": "https://i.imgur.com/4GWj7ru.gif", "name": "Neon Genesis Evangelion" },
    { "url": "https://i.imgur.com/4zDdDTu.gif", "name": "Murenase! Seton Gakuen" },
    { "url": "https://i.imgur.com/1ySBsG0.gif", "name": "Hyperdimension Neptunia" },
    { "url": "https://i.imgur.com/RasLZyz.gif", "name": "Ore no Imōto ga Konna ni Kawaii Wake ga Nai" },
    { "url": "https://i.imgur.com/sRt8mdG.gif", "name": "Haikyū!!" },
    { "url": "https://i.imgur.com/utUsluv.gif", "name": "Hunter x Hunter" },
    { "url": "https://i.imgur.com/bcMES6E.gif", "name": "Ore no Imōto ga Konna ni Kawaii Wake ga Nai" }
],
    "BITE": [
    { "url": "https://i.imgur.com/6Iu2FJJ.gif", "name": "Rewrite" },
    { "url": "https://i.imgur.com/FVYVr7h.gif", "name": "Akame ga Kill!" },
    { "url": "https://i.imgur.com/6OMor5g.gif", "name": "Diabolik Lovers" },
    { "url": "https://i.imgur.com/IGaVGMG.gif", "name": "Servamp" },
    { "url": "https://i.imgur.com/3z063qI.gif", "name": "Kuroshitsuji" },
    { "url": "https://i.imgur.com/5FFEwXY.gif", "name": "Omamori Himari" },
    { "url": "https://i.imgur.com/k01ZRd0.gif", "name": "Monogatari" },
    { "url": "https://i.imgur.com/8isjMri.gif", "name": "GJ-bu" },
    { "url": "https://i.imgur.com/E2HT0PV.gif", "name": "GJ-bu" },
    { "url": "https://i.imgur.com/BhvXK4E.gif", "name": "Eureka Seven" },
    { "url": "https://i.imgur.com/VLxYsvW.gif", "name": "Zombie Land Saga" },
    { "url": "https://i.imgur.com/dr6KIYJ.gif", "name": "CJ-bu" },
    { "url": "https://i.imgur.com/PYlaalk.gif", "name": "Akagami no Shirayuki-hime" },
    { "url": "https://i.imgur.com/Aqy7o4m.gif", "name": "Monogatari" },
    { "url": "https://i.imgur.com/nmVHbrv.gif", "name": "Black Bullet" }
],
    "BLUSH": [
    { "url": "https://i.imgur.com/x6P8rOG.gif", "name": "Darling in the Franxx" },
    { "url": "https://i.imgur.com/IZCTdCD.gif", "name": "Tokyo Ravens" },
    { "url": "https://i.imgur.com/Xxg7ZxM.gif", "name": "Shinmai Maou no Testament" },
    { "url": "https://i.imgur.com/q8y8pVH.gif", "name": "Go-Tōbun no Hanayome" },
    { "url": "https://i.imgur.com/7Xwz84S.gif", "name": "Masamune-Kun Revenge" },
    { "url": "https://i.imgur.com/eDPRKLg.gif", "name": "Kanojo, Okarishimasu" },
    { "url": "https://i.imgur.com/RQZeB1S.gif", "name": "Kono Subarashii Sekai ni Shukufuku wo!" },
    { "url": "https://i.imgur.com/z2pGco4.gif", "name": "Komi-san wa Komyushou Desu" },
    { "url": "https://i.imgur.com/Fudfk55.gif", "name": "Yuru Yuri" },
    { "url": "https://i.imgur.com/Wd94QpT.gif", "name": "Kimi ni Todoke" },
    { "url": "https://i.imgur.com/gvssWJ3.gif", "name": "Hatsukoi Monster" },
    { "url": "https://i.imgur.com/ZZZXKtm.gif", "name": "K-On!" },
    { "url": "https://i.imgur.com/dHffkLz.gif", "name": "Sono Bisque Doll wa Koi wo Suru" },
    { "url": "https://i.imgur.com/Ab3XDGn.gif", "name": "Tsurezure Childre" },
    { "url": "https://i.imgur.com/9P5DRNE.gif", "name": "Kakegurui" }
],
    "CRY": [
    { "url": "https://i.imgur.com/7IzwdD9.gif", "name": "Attack on Titan" },
    { "url": "https://i.imgur.com/x7tYpbv.gif", "name": "Boku Dake ga Inai Machi" },
    { "url": "https://i.imgur.com/jyqhePp.gif", "name": "Shadow House" },
    { "url": "https://i.imgur.com/tUQs3FW.gif", "name": "Toradora!" },
    { "url": "https://i.imgur.com/EKp4YR1.gif", "name": "The Promised Neverland" },
    { "url": "https://i.imgur.com/KqHzuZ7.gif", "name": "Charlotte" },
    { "url": "https://i.imgur.com/ywUqj7q.gif", "name": "The Seven Deadly Sins" },
    { "url": "https://i.imgur.com/60HjzUI.gif", "name": "Gakkō Gurashi!" },
    { "url": "https://i.imgur.com/XdgZyzJ.gif", "name": "Fate/kaleid liner Prisma Illya" },
    { "url": "https://i.imgur.com/xpn1Q83.gif", "name": "Mirai Nikki" },
    { "url": "https://i.imgur.com/gabGglH.gif", "name": "Trinity Seven" },
    { "url": "https://i.imgur.com/chuswxo.gif", "name": "Nagi no Asukara" },
    { "url": "https://i.imgur.com/ZUcjyPv.gif", "name": "Fumetsu no Anata e" },
    { "url": "https://i.imgur.com/1k0Rb9b.gif", "name": "Attack on Titan" },
    { "url": "https://i.imgur.com/T2tVwZv.gif", "name": "Chūnibyō Demo Koi ga Shitai!" }
],
    "DANCE": [
    { "url": "https://i.imgur.com/L8VwJMi.gif", "name": "Macross Delta" },
    { "url": "https://i.imgur.com/av3hJjP.gif", "name": "Little Witch Academia" },
    { "url": "https://i.imgur.com/yKd5UgV.gif", "name": "Sora no Otoshimono" },
    { "url": "https://i.imgur.com/kJSFpEG.gif", "name": "YuruYuri" },
    { "url": "https://i.imgur.com/4YXFUpZ.gif", "name": "Boku wa Tomodachi ga Sukunai" },
    { "url": "https://i.imgur.com/doNfRJ9.gif", "name": "Touhou Project" },
    { "url": "https://i.imgur.com/PZ7h9KX.gif", "name": "Ore no Imōto ga Konna ni Kawaii Wake ga Nai" },
    { "url": "https://i.imgur.com/pp4GSu2.gif", "name": "Zombie Land Saga" },
    { "url": "https://i.imgur.com/r0T7Npf.gif", "name": "Hyouka" },
    { "url": "https://i.imgur.com/Bz155HU.gif", "name": "YuruYuri" },
    { "url": "https://i.imgur.com/nUj0yNn.gif", "name": "Kantai Collection" },
    { "url": "https://i.imgur.com/6Ldh0rE.gif", "name": "Assassination Classroom" },
    { "url": "https://i.imgur.com/OoSj9QS.gif", "name": "Kore wa Zombie Desu ka?" },
    { "url": "https://i.imgur.com/O1Ycs4x.gif", "name": "Yogurting" },
    { "url": "https://i.imgur.com/pShlNBC.gif", "name": "The Idolmaster Cinderella Girls" }
],
    "DEREDERE": [
    { "url": "https://i.imgur.com/TOf6iF5.gif", "name": "Sono Bisque Doll wa Koi wo Suru" },
    { "url": "https://i.imgur.com/mBV1fiw.gif", "name": "Komi-san wa Komyushou Desu" },
    { "url": "https://i.imgur.com/rPlwMPZ.gif", "name": "Cardcaptor Sakura" },
    { "url": "https://i.imgur.com/YvoTz0M.gif", "name": "Ouran Highschool Host Club" },
    { "url": "https://i.imgur.com/8FFlIWf.gif", "name": "Fairy Tail" },
    { "url": "https://i.imgur.com/nJ1mqWU.gif", "name": "Mikakunin de Shinkoukei" },
    { "url": "https://i.imgur.com/RPKcFe8.gif", "name": "Jibaku Shōnen Hanako-kun" },
    { "url": "https://i.imgur.com/YZ1Hpkb.gif", "name": "Love Lab" },
    { "url": "https://i.imgur.com/HG4NFTA.gif", "name": "One Piece" },
    { "url": "https://i.imgur.com/WgrkMV6.gif", "name": "Pokémon" },
    { "url": "https://i.imgur.com/ELvKYq9.gif", "name": "Kamisama Hajimemashita" },
    { "url": "https://i.imgur.com/VnMP0Sq.gif", "name": "Shugo Chara!" },
    { "url": "https://i.imgur.com/JZYxxwz.gif", "name": "Sono Bisque Doll wa Koi wo Suru" },
    { "url": "https://i.imgur.com/2oJQmdd.gif", "name": "Kimetsu no Yaiba" },
    { "url": "https://i.imgur.com/9DiFtPg.gif", "name": "Sono Bisque Doll wa Koi wo Suru" }
],
    "HAPPY": [
    { "url": "https://i.imgur.com/wHivnVp.gif", "name": "Blend S" },
    { "url": "https://i.imgur.com/sVfHROW.gif", "name": "Jibaku Shōnen Hanako-kun" },
    { "url": "https://i.imgur.com/Ib2Zrhw.gif", "name": "BanG Dream!" },
    { "url": "https://i.imgur.com/pFbLxbT.gif", "name": "Jibaku Shōnen Hanako-kun" },
    { "url": "https://i.imgur.com/faT3e13.gif", "name": "Hypnosis Mic: Division Rap Battle: Rhyme Anima" },
    { "url": "https://i.imgur.com/gFI7UWv.gif", "name": "K-On!" },
    { "url": "https://i.imgur.com/8TAtDEf.gif", "name": "Kiznaiver" },
    { "url": "https://i.imgur.com/o5mei2a.gif", "name": "Shigatsu wa kimi no uso" },
    { "url": "https://i.imgur.com/bjUKNMk.gif", "name": "One Piece" },
    { "url": "https://i.imgur.com/JYbFpVy.gif", "name": "SSSS.Gridman" },
    { "url": "https://i.imgur.com/RKeHsEQ.gif", "name": "Tensei Shitara Slime Datta Ken" },
    { "url": "https://i.imgur.com/86gypeq.gif", "name": "Watashi ni Tenshi ga Maiorita!" },
    { "url": "https://i.imgur.com/WhwKs4g.gif", "name": "Fruits Basket" },
    { "url": "https://i.imgur.com/u03OJX2.gif", "name": "The Kingdom of Magic" },
    { "url": "https://i.imgur.com/Zq5KS21.gif", "name": "Noucome" }
],
    "HUG": [
    { "url": "https://i.imgur.com/SOWP0Ai.gif", "name": "Fruits Basket" },
    { "url": "https://i.imgur.com/v5TIAaP.gif", "name": "Sora no Method" },
    { "url": "https://i.imgur.com/IgVYz6C.gif", "name": "Toradora!" },
    { "url": "https://i.imgur.com/hh8Yfyp.gif", "name": "Naruto" },
    { "url": "https://i.imgur.com/INAogzM.gif", "name": "Yuri!!! On Ice" },
    { "url": "https://i.imgur.com/A0irsUq.gif", "name": "K-On!" },
    { "url": "https://i.imgur.com/GxSJxol.gif", "name": "Kaichou wa Maid-sama!" },
    { "url": "https://i.imgur.com/bO1M1Jg.gif", "name": "Kimi ni Todoke" },
    { "url": "https://i.imgur.com/uFIFDiN.gif", "name": "Dragon Ball Super" },
    { "url": "https://i.imgur.com/dqO6Oy0.gif", "name": "Sword Art Online" },
    { "url": "https://i.imgur.com/uOuCSSe.gif", "name": "Adachi to Shimamura" },
    { "url": "https://i.imgur.com/zMcnGrb.gif", "name": "Yuri!!! On Ice" },
    { "url": "https://i.imgur.com/vtYVP6P.gif", "name": "Acchi Kocchi" },
    { "url": "https://i.imgur.com/2XfEpwE.gif", "name": "Free!" },
    { "url": "https://i.imgur.com/xnIWgdk.gif", "name": "Kyoukai no Kanata" }
],
    "KISS": [
    { "url": "https://i.imgur.com/KJV1mwp.gif", "name": "Kiss x Sis" },
    { "url": "https://i.imgur.com/GxiSyvN.gif", "name": "Tonari no Kaibutsu-kun" },
    { "url": "https://i.imgur.com/VPF95zT.gif", "name": "Tokyo Ravens" },
    { "url": "https://i.imgur.com/jh2BeQt.gif", "name": "Suki-tte Ii Na Yo" },
    { "url": "https://i.imgur.com/X46ma2F.gif", "name": "Guilty Crown" },
    { "url": "https://i.imgur.com/rFUl3U2.gif", "name": "Kamisama Hajimemashita" },
    { "url": "https://i.imgur.com/HYngv88.gif", "name": "Naruto" },
    { "url": "https://i.imgur.com/GFjdGUl.gif", "name": "Darling in the Franxx" },
    { "url": "https://i.imgur.com/Ze7WEx8.gif", "name": "Mirai Nikki" },
    { "url": "https://i.imgur.com/GqGfduY.gif", "name": "Toradora!" },
    { "url": "https://i.imgur.com/B1tQXH1.gif", "name": "Chūnibyō Demo Koi ga Shitai!" },
    { "url": "https://i.imgur.com/oj6ECga.gif", "name": "Yosuga no Sora" },
    { "url": "https://i.imgur.com/z1IEncl.gif", "name": "Fruits Basket" },
    { "url": "https://i.imgur.com/kVBAw4V.gif", "name": "Higashi no Eden" },
    { "url": "https://i.imgur.com/JSrDZri.gif", "name": "Golden Time" }
],
    "PAT": [
    { "url": "https://i.imgur.com/twqh3yg.gif", "name": "Acchi Kocchi" },
    { "url": "https://i.imgur.com/NoTd9Po.gif", "name": "Touhou Project" },
    { "url": "https://i.imgur.com/taXwLPM.gif", "name": "Kuroshitsuji" },
    { "url": "https://i.imgur.com/Rl2wWth.gif", "name": "Yagate Kimi ni Naru" },
    { "url": "https://i.imgur.com/8KbD9CN.gif", "name": "New Game!" },
    { "url": "https://i.imgur.com/3Lo2H9a.gif", "name": "Seirei Tsukai no Bladedance" },
    { "url": "https://i.imgur.com/h3JilPg.gif", "name": "Mikakunin de Shinkoukei" },
    { "url": "https://i.imgur.com/F10PWuJ.gif", "name": "Kamisama Hajimemashita" },
    { "url": "https://i.imgur.com/WMM92AS.gif", "name": "Kyoukai no Kanata" },
    { "url": "https://i.imgur.com/Lu5e2H3.gif", "name": "Kono Subarashii Sekai ni Shukufuku wo!" },
    { "url": "https://i.imgur.com/MP9ey45.gif", "name": "Nyarko-san Another Crawling Chaos" },
    { "url": "https://i.imgur.com/GWcvbjA.gif", "name": "Tiger & Bunny" },
    { "url": "https://i.imgur.com/xipUn0x.gif", "name": "Spice and Wolf" },
    { "url": "https://i.imgur.com/K7Fv2Jo.gif", "name": "Seishun Buta Yarō" },
    { "url": "https://i.imgur.com/t4iOydS.gif", "name": "Kotoura-san" }
],
    "PUNCH": [
    { "url": "https://i.imgur.com/pNxou6D.gif", "name": "Fairy Tail" },
    { "url": "https://i.imgur.com/JcvGU4q.gif", "name": "Tokyo Revengers" },
    { "url": "https://i.imgur.com/lLTwuw7.gif", "name": "Dragon Ball Z" },
    { "url": "https://i.imgur.com/I1S6wxx.gif", "name": "Attack on Titan" },
    { "url": "https://i.imgur.com/qrxrFQk.gif", "name": "One Punch Man" },
    { "url": "https://i.imgur.com/SCLppTB.gif", "name": "BNA" },
    { "url": "https://i.imgur.com/X4QmjWs.gif", "name": "Kimetsu no Yaiba: Mugen Ressha-hen" },
    { "url": "https://i.imgur.com/fzX84SX.gif", "name": "Tensei Shitara Slime Datta Ken" },
    { "url": "https://i.imgur.com/oz2cz4N.gif", "name": "Yosuga no Sora" },
    { "url": "https://i.imgur.com/BMw8ZeZ.gif", "name": "Takt Op. Destiny" },
    { "url": "https://i.imgur.com/xOU2FdP.gif", "name": "The Seven Deadly Sins" },
    { "url": "https://i.imgur.com/c9iWN3w.gif", "name": "Love is war" },
    { "url": "https://i.imgur.com/eXKNMSh.gif", "name": "Jutusu Kaisen" },
    { "url": "https://i.imgur.com/1O0WFuf.gif", "name": "Attack on Titan" },
    { "url": "https://i.imgur.com/kpOZmTG.gif", "name": "The Rolling Girls" }
],
    "SLAP": [
    { "url": "https://i.imgur.com/c9iWN3w.gif", "name": "Love is War" },
    { "url": "https://i.imgur.com/JYYro1Z.gif", "name": "KonoSuba!" },
    { "url": "https://i.imgur.com/y9nAWIU.gif", "name": "Boku wa Tomodachi ga Sukunai" },
    { "url": "https://i.imgur.com/PO7Hkk9.gif", "name": "Shinryaku! Ika Musume" },
    { "url": "https://i.imgur.com/mDtOff5.gif", "name": "Chunibiyou Demo Koi ga Shitai!" },
    { "url": "https://i.imgur.com/GSHhSbe.gif", "name": "Gabriel DropOut" },
    { "url": "https://i.imgur.com/3s41PZ2.gif", "name": "Golden Time" },
    { "url": "https://i.imgur.com/3wdq4M5.gif", "name": "Golden Time" },
    { "url": "https://i.imgur.com/Zqfzxpr.gif", "name": "Tokyo Revengers" },
    { "url": "https://i.imgur.com/Rh5Cw1V.gif", "name": "Toradora!" },
    { "url": "https://i.imgur.com/nDzKXlG.gif", "name": "Mushoku Tensei: Isekai Ittara Honki Dasu" },
    { "url": "https://i.imgur.com/DcIvIOe.gif", "name": "Plastic Nee-san" },
    { "url": "https://i.imgur.com/BPFjDvT.gif", "name": "Love Lab" },
    { "url": "https://i.imgur.com/BKuYlKS.gif", "name": "Kanojo mo Kanojo" },
    { "url": "https://i.imgur.com/2Yd6bW4.gif", "name": "Yuru Yuri" }
],
    "SLEEP": [
    { "url": "https://i.imgur.com/eBI6QLh.gif", "name": "Attack on Titan" },
    { "url": "https://i.imgur.com/GWh6Zr8.gif", "name": "Spice and wolf" },
    { "url": "https://i.imgur.com/5OzYVsN.gif", "name": "Naruto" },
    { "url": "https://i.imgur.com/c1c9CWJ.gif", "name": "The Idolmaster Cinderella Girls" },
    { "url": "https://i.imgur.com/lLhyorw.gif", "name": "Gakusen Toshi Asterisk" },
    { "url": "https://i.imgur.com/MOR3XAc.gif", "name": "En'en no Shōbōtai" },
    { "url": "https://i.imgur.com/UleOlI1.gif", "name": "Kamisama Hajimemashita" },
    { "url": "https://i.imgur.com/ZgoJdOd.gif", "name": "K-On!" },
    { "url": "https://i.imgur.com/W2yUeN0.gif", "name": "Chūnibyō Demo Koi ga Shitai!" },
    { "url": "https://i.imgur.com/82K8wiQ.gif", "name": "Suzumiya Haruhi no Yūutsu" },
    { "url": "https://i.imgur.com/jWCTilg.gif", "name": "Lovely complex" },
    { "url": "https://i.imgur.com/fr59Wfr.gif", "name": "Sakura-sō no Pet na Kanojo" },
    { "url": "https://i.imgur.com/hIqMhAG.gif", "name": "Little Busters!" },
    { "url": "https://i.imgur.com/zF9670x.gif", "name": "YuruYuri" },
    { "url": "https://i.imgur.com/DXQgPBz.gif", "name": "Charlotte" }
],
    "SMUG": [
    { "url": "https://i.imgur.com/I5vf87f.gif", "name": "K-On!" },
    { "url": "https://i.imgur.com/DsOKeTX.gif", "name": "Dr. Stone" },
    { "url": "https://i.imgur.com/WccH8Uj.gif", "name": "Darling in the Fraxx" },
    { "url": "https://i.imgur.com/Phpu0VO.gif", "name": "Nisekoi" },
    { "url": "https://i.imgur.com/6VNnfAY.gif", "name": "Nikesoi" },
    { "url": "https://i.imgur.com/ZfEo1DX.gif", "name": "Kawaikereba Hentai demo Suki ni Natte Kuremasuka?" },
    { "url": "https://i.imgur.com/CPJIM43.gif", "name": "Gakkō Gurashi!" },
    { "url": "https://i.imgur.com/5MdfYIw.gif", "name": "Hyperdimension Neptunia" },
    { "url": "https://i.imgur.com/N7CrBuq.gif", "name": "Black Bullet" },
    { "url": "https://i.imgur.com/WcGLj3W.gif", "name": "Danganronpa 2: Goodbye Despair" },
    { "url": "https://i.imgur.com/moONrO2.gif", "name": "Noragami" },
    { "url": "https://i.imgur.com/i7SFPW5.gif", "name": "Kono Subarashii Sekai ni Shukufuku wo!" },
    { "url": "https://i.imgur.com/aopzG0u.gif", "name": "Inu x Boku Secret Service" },
    { "url": "https://i.imgur.com/zdU1IGI.gif", "name": "Hyouka" },
    { "url": "https://i.imgur.com/HsoQ5FL.gif", "name": "Zoombie Land Saga" }
]
}